.ALIASES
V_V1            V1(+=N00204 -=0 ) CN @FSD.SCHEMATIC1(sch_1):INS26@SOURCE.VDC.Normal(chips)
R_R1            R1(1=N00204 2=N00186 ) CN @FSD.SCHEMATIC1(sch_1):INS51@ANALOG.R.Normal(chips)
R_R2            R2(1=0 2=N00186 ) CN @FSD.SCHEMATIC1(sch_1):INS67@ANALOG.R.Normal(chips)
R_R3            R3(1=0 2=N00186 ) CN @FSD.SCHEMATIC1(sch_1):INS83@ANALOG.R.Normal(chips)
L_L1            L1(1=N00186 2=N00149 ) CN @FSD.SCHEMATIC1(sch_1):INS108@ANALOG.L.Normal(chips)
X_U1            U1(1=0 2=N00149 ) CN @FSD.SCHEMATIC1(sch_1):INS133@EVAL.Sw_tClose.Normal(chips)
.ENDALIASES
